" Configuration for gvim

" Use console dialogs instead of popups, enable the gvim window icon, and enable
" a scroll bar on the right side of the window.
set guioptions=cir

" Enable the mouse everywhere
set mouse=a

" Fonts
if has('gui_gtk')
    " Gtk2 and Gtk3
    set guifont=Hack\ 10
elseif has('gui_win32')
    " Windows
    set guifont=Terminus:h8:cANSI
endif
