" Make vim incomaptible with vi, usually this is redundant, but I have run into
" cases where it does make a difference.
set nocompatible

" Syntax colors
syntax on

" Filetype plugins
filetype plugin on
filetype plugin indent on

" Get user's vim config directory (used later)
let g:user_config_dir = split(&rtp, ',')[0]

exe 'source ' . g:user_config_dir . '/plugins.vim'
exe 'source ' . g:user_config_dir . '/mappings.vim'
exe 'source ' . g:user_config_dir . '/options.vim'
exe 'source ' . g:user_config_dir . '/colorscheme.vim'
exe 'source ' . g:user_config_dir . '/indentation.vim'
exe 'source ' . g:user_config_dir . '/autocommands.vim'
exe 'source ' . g:user_config_dir . '/statusline.vim'
