#!/usr/bin/env bash

# Use i3status to get battery status
line="$(i3status -c $HOME/.i3/blocks/i3status-battery.conf 2>/dev/null | head -n1)"
[[ $line = "No battery" ]] && exit 0

PARTS=($line)

CHARGE="${PARTS[1]}"
CHARGE="${CHARGE%\%*}"
[[ "${CHARGE}" -gt 100 ]] && {
    CHARGE="100"
}

STATE=""
if [[ "${PARTS[0]}" = "BAT" ]]; then
    STATE="${PARTS[2]}"
    [[ -n "${STATE}" ]] && {
        STATE="(${STATE:0:-6})"
    }
elif [[ "${PARTS[0]}" = "CHR" ]]; then
    STATE="(charging)"
fi

LEVEL=$(( (CHARGE - 1) / 20 ))
# ICON="f$(( 244 - LEVEL ))"

echo -e "Bat: ${CHARGE}% ${STATE}"

[[ "${LEVEL}" = "0" ]] && {
    [[ -z "${STATE}" ]] || i3-msg "fullscreen disable" >/dev/null
}

exit 0
