#!/usr/bin/env bash
if command -v pacman >/dev/null; then
    UPDATES="$(checkupdates | wc -l)"
    [[ ! $UPDATES = "0" ]] && TEXT="Updates: $UPDATES"
    if command -v yay >/dev/null; then
        AUR="$(yay -Qquam | wc -l)"
        [[ ! $AUR = "0" ]] && TEXT=" $TEXT (AUR: $AUR) "
    fi
fi

echo "$TEXT"
echo "$TEXT"
exit 0
