#!/usr/bin/env bash
if command -v pacman >/dev/null; then
    UPDATES="$(checkupdates | wc -l)"
    [[ ! $UPDATES = "0" ]] && TEXT="$UPDATES"
    if command -v pacaur >/dev/null; then
        AUR="$(pacaur -Qquam | wc -l)"
        [[ ! $AUR = "0" ]] && TEXT="$TEXT  $AUR"
    fi
fi

echo "$TEXT"
echo "$TEXT"
exit 0
