#!/usr/bin/env bash

case $BLOCK_BUTTON in
    1)
        ~/.i3/i3dialog -t -o '0,-22' -- 'termite -e "nmtui-connect"' &
        ;;
    3)
        ~/.i3/i3dialog -t -o '0,-22' -- 'termite -e "nmtui-edit"' &
        ;;
esac

TEXT="Wifi"
echo "$TEXT"
echo "$TEXT"
