#!/usr/bin/env bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

if [[ -n $BLOCK_INSTANCE ]]; then
    INTERFACE="$BLOCK_INSTANCE"
else
    INTERFACE="$(ip route | awk '/^default/ { print $5 }')"
fi

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
if [[ -z $INTERFACE ]]; then
  exit 1
fi

#------------------------------------------------------------------------

QUALITY=$(grep "$INTERFACE" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

echo "$QUALITY%" # full text
echo "$QUALITY%" # short text

# color
[[ $QUALITY -lt 40 ]] && echo "#FF0000"

exit 0
