#!/usr/bin/env bash

case $BLOCK_BUTTON in
    1)
        if xlsclients -l | grep -q "Instance.*__nmtui"; then
            i3-msg '[instance="__nmtui"] kill' >/dev/null
        else
            termite -e 'nmtui-connect' --name '__nmtui' >/dev/null 2>&1 &
        fi
        ;;
    3)
        if xlsclients -l | grep -q "Instance.*__nmtui"; then
            i3-msg '[instance="__nmtui"] kill' >/dev/null
        else
            termite -e 'nmtui-edit' --name '__nmtui' >/dev/null 2>&1 &
        fi
        ;;
esac

TEXT=""
echo "$TEXT"
echo "$TEXT"
