#!/usr/bin/env bash

lock () {
	if command -v scrot >/dev/null 2>&1; then
		~/.i3/i3lock-fancy -- scrot
	else
		~/.i3/i3lock-fancy
	fi
}

case "$1" in
	lock)
		lock
		;;
	logout)
		i3-msg exit
		;;
	suspend)
		lock
		sleep 1
		systemctl suspend
		;;
	hibernate)
		systemctl hibernate
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
		exit 2
esac

exit 0
