############################
# Evergreen's bash_profile #
############################

[[ -f ~/.bash_profile.local ]] && source ~/.bash_profile.local

# Source bashrc if it exists.  Environment variables are set in bashrc before
# the interactivity check.
[[ -f ~/.bashrc ]] && source ~/.bashrc
